### ISSUE TITLE
How can I get client_static_keypair?

### ISSUE THREAD

**Issue by endroemily** [lovethiscode/Gorgeous-Whatsapp#1]
Hello @lovethiscode 
Congratulations, i see you solved the problem. 
How can I get client_static_keypair instead of client_static_keypair_pwd_enc.
How can we use it, what compiler should we use it with, and what should we do? Can you explain these?
Kind Regards.

**Comment by GM12Tick** [comment]
I think its more important to be able to convert all of the settings into yowsup.config file.

@lovethiscode 
Just wondering, i see the Tool is used to parse the files locally, but it doesn't output it to a yowsup.config and axolotl.db in format for yowsup, right?

**Comment by lovethiscode** [comment]
In the Tool directory is an Android Tool. The extracted environment is not the config used by Yowsup, but the configuration file used in my own project. 

The Java project has a JNI function, StringFromJNI,。 and calls this JNI function to decrypt data。

**Comment by lovethiscode** [comment]
Under the Gorgeous directory is a Java project that supports Windows and Linux. This project, like Yowsup, provides login, message, etc., and is currently in the process of being improved

**Comment by lovethiscode** [comment]
If you can send a complete yowsup.config demo file to me, I can export the yowsup.config file

**Comment by lovethiscode** [comment]
> I think its more important to be able to convert all of the settings into yowsup.config file.
> 
> @lovethiscode
> Just wondering, i see the Tool is used to parse the files locally, but it doesn't output it to a yowsup.config and axolotl.db in format for yowsup, right?

If you can send a complete yowsup.config demo file to me, I can export the yowsup.config file
