### ISSUE TITLE
消息类型mediatype='sticker'  protobuf无法解析

### ISSUE THREAD

**Issue by DebugNewWorld** [lovethiscode/Gorgeous-Whatsapp#10]
`String stickerMessage_byteString = "0gHRAgpNaHR0cHM6Ly9tbWcud2hhdHNhcHAubmV0L2QvZi9BcU95Rk1NRHpubld6a3lFaE1YYWphcFRXRjByWmFkenB0bVBvZGVXSGwzaS5lbmMSIBTa0l6Vmw9Pqnt+pgk2grKJPyAgpmN3Vk9hijJw5+q0GiALF6O57bucu7PdjYxpmu4fUjEz60KiIi2qXUPKIl0VuCIgpYOODiHpaKTnW1nYN64DJWXWJXFwPMedBYz3gVQsdJIqCmltYWdlL3dlYnAwgAQ4gARCci92L3Q2Mi4xNTU3NS0yNC8zMDk0Mjc2MF83NDY5MTk5NDYwMTQyOTdfMTkzNDU1MDE0NjkxNzcwMzIwMV9uLmVuYz9vaD1jMGVkYzRiMzJlZWNkN2VmOTgwNWE2NTcwZDdmYzQ3NSZvZT02MDdENzBFREjU7wRQ8N/LggZoAIoBB9AB+drLggY=";
WhatsMessage.WhatsAppMessage msg = WhatsMessage.WhatsAppMessage.parseFrom(plainText);
System.err.println(msg);`

输出: 
26: {
    1: "https://mmg.whatsapp.net/d/f/AqOyFMMDznnWzkyEhMXajapTWF0rZadzptmPodeWHl3i.enc"
    2: "\024\332\322^\225\233\017O\252{~\246\t6\202\262\211?  \246cwVOa\2122p\347\352\264"
    3: "\v\027\243\271\355\273\234\273\263\335\215\214i\232\356\037R13\353B\242\"-\252]C\312\"]\025\270"
    4: "\245\203\216\016!\351h\244\347[Y\3307\256\003%e\326%qp<\307\235\005\214\367\201T,t\222"
    5: "image/webp"
    6: 512
    7: 512
    8: "/v/t62.15575-24/30942760_746919946014297_1934550146917703201_n.enc?oh=c0edc4b32eecd7ef9805a6570d7fc475&oe=607D70ED"
    9: 79828
    10: 1616048112
    13: 0
    17: {
      26: 1616047481
    }
}

Process finished with exit code 0

![image](https://user-images.githubusercontent.com/24141885/111585825-dd576c80-87fa-11eb-98a1-9f11069f62b6.png)

**Comment by lovethiscode** [comment]
后续再支持吧。

**Comment by lovethiscode** [comment]
@DebugNewWorld 已经支持了

**Comment by DebugNewWorld** [comment]
可以了
