### ISSUE TITLE
请问一下这个lib库  对whatsapp 的版本有关系吗？

### ISSUE THREAD

**Issue by TTDemo** [lovethiscode/Gorgeous-Whatsapp#11]
1. 我根究你的文档，安装了Android端 数据库导出 工具，并导出数据库到sdcard， 在登陆的时候选择了导出数据库。但是在握手的时候提示如下错误：

选择服务器:e6.whatsapp.net
start HandshakeIK
check whatsapp version NoiseJni.CheckWhatsappVersion

我想应该是我的android 端 whatsapp版本有问题， 和您确认你的这个WhatsApp lib 支持whatsapp 版本有哪些

**Comment by lovethiscode** [comment]
whatsapp 经常更新所以所以要先调用一下 NoiseJni.CheckWhatsappVersion  来检查版本。 返回success 才能使用。

**Comment by TTDemo** [comment]
我现在使用的过程中，返回值是failed， 如何才能让他sucess

**Comment by lovethiscode** [comment]
提问的一些基本原则
尽量把错误信息全部贴出来， 你说返回 failed。 具体是什么错误？

会去 访问 https://www.whatsapp.com/android/  这个网站检查版本，你自己确认好能不能访问，如果不能就自己设置代理
