### ISSUE TITLE
Gorgeous工程run时报错

### ISSUE THREAD

**Issue by wangqiang20000909** [lovethiscode/Gorgeous-Whatsapp#12]
> Task :compileJava UP-TO-DATE
> Task :processResources NO-SOURCE
> Task :classes UP-TO-DATE

> Task :MainDialog.main()
Exception in thread "main" java.awt.IllegalComponentStateException: contentPane cannot be set to null.
	at javax.swing.JRootPane.setContentPane(JRootPane.java:621)
	at javax.swing.JDialog.setContentPane(JDialog.java:1047)
	at MainDialog.<init>(MainDialog.java:71)
	at MainDialog.main(MainDialog.java:469)

**Comment by wangqiang20000909** [comment]
@lovethiscode

**Comment by lovethiscode** [comment]
File--->Settings---->Build,xxx ---->Build Tools---->Gradle--->Build and run using---> Intellij IDEA

**Comment by wangqiang20000909** [comment]
> File--->Settings---->Build,xxx ---->Build Tools---->Gradle--->Build and run using---> Intellij IDEA

非常感谢，比较奇怪的是我的Androidstudio（版本4.1.3）里面没有这个设置项（以下附图），是不是我少安装了什么插件吗

![微信截图_20210322101703](https://user-images.githubusercontent.com/79240436/111936376-1abc4280-8af8-11eb-8529-cd9916908b4b.png)

**Comment by lovethiscode** [comment]
这个是java 的工程， 我用的IntelliJ IDEA 。
另外这个工程依赖的JNI 不能在android上运行，so 文件是运行在 linux系统的。

**Comment by wangqiang20000909** [comment]
> 这个是java 的工程， 我用的IntelliJ IDEA 。
> 另外这个工程依赖的JNI 不能在android上运行，so 文件是运行在 linux系统的。

okay，谢了
