### ISSUE TITLE
video Tutorial required 

### ISSUE THREAD

**Issue by madhu9998** [lovethiscode/Gorgeous-Whatsapp#13]
hello

Thank you for helping the community 

is there any tutorial in video format available from Compiling the Source code in JAVA,taking the DB from emulator or mobile phone ,extraction tool and sending the first message

it will be very helpful for the first timers

**Comment by lovethiscode** [comment]
There is no video tutorial, so the account registration is really troublesome. The function of automatic account registration is under development, and it needs some time to complete the verification.

@madhu9998

**Comment by madhu9998** [comment]
> There is no video tutorial, so the account registration is really troublesome. The function of automatic account registration is under development, and it needs some time to complete the verification.
> 
> @madhu9998

Hello 

Can you ping me on any telegram my username @madhu9998 

need to speak abt some proposal

**Comment by madhu9998** [comment]
Hello

how can I get in contact with you directly ??

**Comment by lovethiscode** [comment]
ok,  I will contact you with Telegram later.
