### ISSUE TITLE
Is there a "Gorgeous-Whatsapp-cli"  like the "yowsup-cli" demos ?

### ISSUE THREAD

**Issue by lauriolasw** [lovethiscode/Gorgeous-Whatsapp#15]
Hello

Is there a "Gorgeous-Whatsapp-cli" that will run on a bash shell without GUI, like the "yowsup-cli" demos ?

Great work !!

**Comment by lovethiscode** [comment]
There is no such tool for the time being, it can be added in the later plan.

**Comment by lovethiscode** [comment]
published
