### ISSUE TITLE
can i convert axolotl.db from yowsup to gorgeous?

### ISSUE THREAD

**Issue by bahtiarp** [lovethiscode/Gorgeous-Whatsapp#16]
I plan to migrate my yowsup number (axolotl.db created by yowsup + config.json)
to gorgeous, is it possible?

thanks.

**Comment by lovethiscode** [comment]
Yowsup has two profiles and Gorgeous has only one, but you can turn Yowsup's profile into Gorgeous.
Gorgeous's database has a config table with an env field that is a protocol buffer. Simply convert yowsup's config to a protocol buffer and store it in this field.

@bahtiarp

**Comment by bahtiarp** [comment]
> Yowsup has two profiles and Gorgeous has only one, but you can turn Yowsup's profile into Gorgeous.
> Gorgeous's database has a config table with an env field that is a protocol buffer. Simply convert yowsup's config to a protocol buffer and store it in this field.
> 
> @bahtiarp

thanks @lovethiscode 
btw do you have windows lib for: "native-lib", so i can create env filed without android studio?

**Comment by lovethiscode** [comment]
There is no Windows version yet, but it may be available in the future.
