### ISSUE TITLE
Alert: Whatshapp Version is Older.

### ISSUE THREAD

**Issue by bahtiarp** [lovethiscode/Gorgeous-Whatsapp#23]
When run the JavaFx launcher today, i got alert: "Whatshapp Version is Older"
What should i do?
![older](https://user-images.githubusercontent.com/3410804/115712362-e362df00-a39e-11eb-93c4-abbc2fb318a0.jpg)

**Comment by Lapa-tik-tik** [comment]
I have the same error on old (for intellij idea) and new version of program :(

**Comment by lovethiscode** [comment]
I need to work during the week and will update on weekends

**Comment by lovethiscode** [comment]
If someone is willing to donate, I will update quickly, otherwise I will only update over the weekend.

**Comment by lovethiscode** [comment]
It is already updated.
