### ISSUE TITLE
[SQLITE_ERROR] SQL error or missing database (no such table: settings)

### ISSUE THREAD

**Issue by elvishoo** [lovethiscode/Gorgeous-Whatsapp#25]
I have compiled Gorgeous and run it,when I use axolotl.db to login,it display a exception "[SQLITE_ERROR] SQL error or missing database (no such table: settings)".I open the axolotl.db but can not find the setting table.

**Comment by lovethiscode** [comment]
how do you get the  axolotl.db?

**Comment by bahtiarp** [comment]
> I have compiled Gorgeous and run it,when I use axolotl.db to login,it display a exception "[SQLITE_ERROR] SQL error or missing database (no such table: settings)".I open the axolotl.db but can not find the setting table.

you have to use axolotl.db that generated by yowsup_config_tool.apk

**Comment by elvishoo** [comment]
> how do you get the axolotl.db?

yes of course,backup use the config tool

**Comment by elvishoo** [comment]
I checked the logcat of config tool.It shows "chmod failed: EPERM (Operation not permitted)" error when chmod of the axolotl.db in the backup directory,so config tool can not create settings table in the axolotl.db.

**Comment by lovethiscode** [comment]
Maybe there is a permission issue on a higher version of Android, I will see what the problem is and fix it

**Comment by lovethiscode** [comment]
> Maybe there is a permission issue on a higher version of Android, I will see what the problem is and fix it

What is the Android version?

**Comment by elvishoo** [comment]
> > Maybe there is a permission issue on a higher version of Android, I will see what the problem is and fix it
> 
> What is the Android version?

Android 7.1 in the Leidian Emulator

**Comment by elvishoo** [comment]
Android 5 in the Leidian Emulator can not create table too,can you give me your enviroment? @lovethiscode

**Comment by lovethiscode** [comment]
The problem has been fixed. You can try again

**Comment by elvishoo** [comment]
> The problem has been fixed. You can try again

No error now,nice work 👍

**Comment by totynho** [comment]
W FileUtils: Failed to chmod(/sdcard/Gorgeous/1627065852/axolotl.db): android.system.ErrnoException: chmod failed: EPERM (Operation not permitted)
 
 not working now... Using MEMU EMULATOR with Android 7.1 (64bits), rooted
