### ISSUE TITLE
What will happen after May 15 

### ISSUE THREAD

**Issue by bahtiarp** [lovethiscode/Gorgeous-Whatsapp#26]
What will happen after May 15 if you do not accept privacy terms for yowsup and gorgeous? How to accept TOS gorgeous? Any idea?

**Comment by lovethiscode** [comment]
I don't know what you mean by that

**Comment by sorosons** [comment]
is that project get online offline status like whatsapp reveng

**Comment by bahtiarp** [comment]
> I don't know what you mean by that

https://github.com/lovethiscode/Gorgeous-Whatsapp/issues/26#issuecomment-832507678

**Comment by bahtiarp** [comment]
> > I don't know what you mean by that
> > [https://www.business-standard.com/article/technology/whatsapp-what-will-happen-after-may-15-if-you-do-not-accept-privacy-terms-121022300783_1.html](url)
