### ISSUE TITLE
On 15th May, all must accept Privacy TOS from Whatsapp.

### ISSUE THREAD

**Issue by bahtiarp** [lovethiscode/Gorgeous-Whatsapp#28]
https://www.business-standard.com/article/technology/whatsapp-what-will-happen-after-may-15-if-you-do-not-accept-privacy-terms-121022300783_1.html

Based on that news , if we dont accept Privacy TOS by 15th May 2021, then we cannot send/receive Whatsapp messages.
Data will be deleted If users still do not accept the new privacy terms by the end of the 120 days after May 15, 
How gorgeous anticipate this or how to accept the Privacy TOS?

**Comment by lovethiscode** [comment]
How do I accept this on the WhatsApp client?

**Comment by bahtiarp** [comment]
As far as i know now, TOS popup will appear at random time.
i got this yesterday:
![tos2](https://user-images.githubusercontent.com/3410804/117307073-7412e200-aeaa-11eb-8437-93532263b685.jpg)
![tos1](https://user-images.githubusercontent.com/3410804/117307076-75dca580-aeaa-11eb-9573-e760f5a7e0ad.jpg)
