### ISSUE TITLE
Export complete yowsup config axolotl.db for yowsup

### ISSUE THREAD

**Issue by lovethiscode** [lovethiscode/Gorgeous-Whatsapp#3]
I have exported the configuration file of Yowsup. If you need to export the axolotl.db , you need to give me a template so that I can export the axolotl.db of WhatsApp. send one to me: jinxing007x@outlook.com

yowsup_config_tool.apk can help you. https://github.com/lovethiscode/Gorgeous-Whatsapp

**Comment by GM12Tick** [comment]
This requires Root access due to "RootShell" dependency. How would you allow this on emulator or can we somehow bypass root requirements?

( I can change code to work from /tmp instead, but i'm thinking if we have some way to not use "RootShell" that require root access)
