### ISSUE TITLE
Login failed on Ubuntu OS

### ISSUE THREAD

**Issue by Lapa-tik-tik** [lovethiscode/Gorgeous-Whatsapp#32]
Hello.

I can successfully launch a whatsapp account from axolotl.db on Mac OS with logs of login:
Transition from 'Init' to 'WaitFinish' on event 'SendClientHello' with context 'Handshake.NoiseHandshake@34aad7c2'.
Transition from 'WaitFinish' to 'Finish' on event 'SendClientFinish' with context 'Handshake.NoiseHandshake@34aad7c2'.
Transition from 'Finish' to 'ChannelReady' on event 'Notify' with context 'Handshake.NoiseHandshake@34aad7c2'.
or
Transition from 'Init' to 'Finish' on event 'SendPayload' with context 'Handshake.NoiseHandshake@4db7cdab'.
Transition from 'Finish' to 'ChannelReady' on event 'Notify' with context 'Handshake.NoiseHandshake@4db7cdab'.

But when I try to run the same account (axolotl.db) from the Ubuntu OS, it does not login with the log:
Transition from 'Init' to 'Finish' on event 'SendPayload' with context 'Handshake.NoiseHandshake@251b7b88'.
and then nothing...

libssl-dev and libcurl4-openssl-dev installed on Ubuntu OS.

**Comment by totynho** [comment]
Same problem here, Windows 10
