### ISSUE TITLE
Unable to find setting table in axolotl.db

### ISSUE THREAD

**Issue by AkashVirani** [lovethiscode/Gorgeous-Whatsapp#33]
When I am trying to login using java client, It is not able to find setting table in db file.

I have generated db file using apk provided in repo, I have checked all the generated db under database folder but none of the has the setting table and without that we won't be able to login

Can anyone help me with either generating db with setting table or how we can by pass that in code.

Many thanks in advance

**Comment by lovethiscode** [comment]
I've updated the tools,
try again.

**Comment by AkashVirani** [comment]
@lovethiscode : thanks, its working now.
But when I am trying to add new contact, I am getting 401 from server and code is breaking with null pointer.

Can you please guide on that?
