### ISSUE TITLE
Not able to send message to groups

### ISSUE THREAD

**Issue by berkercanatar** [lovethiscode/Gorgeous-Whatsapp#37]
Hi,
I am having problem when I try to send messages to groups.
It works well without any problem when messaging to a person. But, when I add bot to a group, especially with 3 or more members, the bot can only send first a few messages to a group and then it becomes unable to send to groups.

To test it, I wrote simple app which echoes messages and it could only 2 echo messages to the group and stop sending. It only happens when sending to group, no problem with private messaging.

Additionally, SendText function runs without problem, does not throw any exception, but message is simply not sent.

I just wanted to ask is there anyone who encounter with this problem too? Is this a bug or did it only happen to me? Thanks.

**Comment by lovethiscode** [comment]
i have just fixed @berkercanatar

**Comment by berkercanatar** [comment]
It seems to be solved, thanks so much.
