### ISSUE TITLE
Can't parse message of type "xauth.response" because it is missing required fields: code, signature 

### ISSUE THREAD

**Issue by GTZCrow** [lovethiscode/Gorgeous-Whatsapp#39]
NoiseJni.InitData(routingInfo)报错，
Can't parse message of type "xauth.response" because it is missing required fields: code, signature

**Comment by lovethiscode** [comment]
项目不在更新了，感觉做这个毫无意义的事情，浪费了大量的时间。

**Comment by Totonator** [comment]
@lovethiscode very sad, great project. Started to get acquainted with it about a week ago and such bad news. 
Do you consider sharing sources of libNoiseJni library to allow developers continue to work with this project?
