### ISSUE TITLE
Help project

### ISSUE THREAD

**Issue by netfiretec** [lovethiscode/Gorgeous-Whatsapp#4]
@lovethiscode Hello friend, would it be possible to chat by instant messenger?

+5538991026786 Whatsapp | Telegram
Skype: netfiretec

**Comment by lovethiscode** [comment]
You can briefly describe what you want to know?
i will help you if i can.

**Comment by netfiretec** [comment]
@lovethiscode 
Call me on one of the instant messengers, we can talk better over there.

**Comment by lovethiscode** [comment]
I already sent you a message, but you didn't reply to me. I'm in Thailand, so I might have a different time zone.
@netfiretec

**Comment by netfiretec** [comment]
Hello colleague, at what stage is your API?
What has been implemented so far?
Is it working on all implementations?

**Comment by lovethiscode** [comment]
login
sendtext
sendmedia(image,audio,video,document)
creategroup, invitegroup..

It implements almost all the functions of WhatsApp, and you can find the corresponding function in the source code

**Comment by netfiretec** [comment]
@lovethiscode Does he also receive Whatsapp messages?

**Comment by lovethiscode** [comment]
Of course. There is a complete interface in the source code. All the WhatsApp functions are there

**Comment by netfiretec** [comment]
Have you documented the process you are using to reverse the engineering of Whatsapp?
