### ISSUE TITLE
Missing source code of the webservice

### ISSUE THREAD

**Issue by CyberPK** [lovethiscode/Gorgeous-Whatsapp#47]
Where can it be found?

**Comment by lovethiscode** [comment]
done

**Comment by lovethiscode** [comment]
just uploaded to github。

**Comment by CyberPK** [comment]
Thank you but I was referencing to the backend running on the Test Server 8.210.124.139:16090 that you bring up "Considering that many people will not deploy, a test server is deployed here for testing only". I would like to deploy my own if you don't mind

If I'm not wrong, the last commit containing an outdated version of the sources is https://github.com/lovethiscode/Gorgeous-Whatsapp/tree/336f1c6673fc0db462e839e954ba7f2c96abf09f
