### ISSUE TITLE
linux sendmedia problem

### ISSUE THREAD

**Issue by 18712886438** [lovethiscode/Gorgeous-Whatsapp#5]
after I login and try to send media fie.

```
Gorgeous-Whatsapp/Gorgeous/jni/libNoiseJni.so: undefined symbol: _Z12RandomStringB5cxx11i
```

**Comment by lovethiscode** [comment]
Linux systems depend on the environment. I haven't tested all Linux systems, but you can start with Windows and Mac systems. You can send me the system information and I will try to fix it and fix the problem.

**Comment by 18712886438** [comment]
> Linux systems depend on the environment. I haven't tested all Linux systems, but you can start with Windows and Mac systems. You can send me the system information and I will try to fix it and fix the problem.

ubuntu 18.04. I will try with windows

**Comment by lovethiscode** [comment]
thanks， i will try and fix. @18712886438

**Comment by lovethiscode** [comment]
I have fixed the problem and can test it with the latest version.
@18712886438

**Comment by 18712886438** [comment]
> I have fixed the problem and can test it with the latest version.
> @18712886438

fixed
