### ISSUE TITLE
SetPushName function It didn't work

### ISSUE THREAD

**Issue by githubXiamo** [lovethiscode/Gorgeous-Whatsapp#6]
https://github.com/lovethiscode/Gorgeous-Whatsapp/blob/43e12ceec616f4d1a14bf48fa13a3560314ba030/Gorgeous/src/main/java/GorgeousEngine.java#L662

**Comment by lovethiscode** [comment]
thanks
 this is a bug,  i will fix it.

**Comment by lovethiscode** [comment]
I have fixed the problem and can test it with the latest version.
@githubXiamo

**Comment by githubXiamo** [comment]
@lovethiscode

I try to modify it like this, and it works.
https://github.com/lovethiscode/Gorgeous-Whatsapp/blob/43e12ceec616f4d1a14bf48fa13a3560314ba030/Gorgeous/src/main/java/GorgeousEngine.java#L661
`
presence.AddAttribute(new StanzaAttribute("type", "available"));
`

output: 发送 \<presence type='available' name='NewPushname'/>

**Comment by lovethiscode** [comment]
You are right. I was negligent. It has been corrected.
@githubXiamo
