### ISSUE TITLE
请问NoiseJni是如何编译出来的。

### ISSUE THREAD

**Issue by handeslfy** [lovethiscode/Gorgeous-Whatsapp#8]
大佬请问如何编译NoiseJni给c#使用。能否告知编译方式呢？谢谢

**Comment by lovethiscode** [comment]
维护一份java 的就耗费了所有时间，没有空再去弄C#得。
近期不会支持C#

**Comment by handeslfy** [comment]
嗯，理解。想请问大佬，编译成libNoiseJni.dylib 的源码是基于 https://github.com/OuterCorner/Noise/吗？如果是的话，请教如何能做到跨平台编译的，请大佬支教，或者丢个链接。

**Comment by lovethiscode** [comment]
不是，我是完全自己写的。
