### ISSUE TITLE
question: Has a way to use Gorgeous only to maintain WhatsApp Web running?

### ISSUE THREAD

**Issue by totynho** [lovethiscode/Gorgeous-Whatsapp#9]
Hello, i'm from brazil and sorry about my english. It's possible someday use your application just to maintain WhatsApp Web running without use a real smartphone or emulator to do this?

**Comment by lovethiscode** [comment]
This app can run on many systems, such as windows, mac, linux systems, without relying on mobile phones or emulators

@totynho

**Comment by totynho** [comment]
You didn't understand. I wanna know If is possible use gorgeous instead of android version only to maintain online my whatsapp web. Replacing the smartphone with this application... Because I have a running application developed in whatsapp-web base and is very "expensive" pay a VPS to run a android emulator... You understand me? Sorry for my english

**Comment by lovethiscode** [comment]
You can turn my application into a web application that doesn't depend on any emulator or phone. It can run independently on a computer. You can deploy an application to a Linux system and then develop a Web application that customers can access directly from the Web

**Comment by totynho** [comment]
I'm sorry ... I'm really not able to explain what I mean ...

**Comment by githubXiamo** [comment]
I guess he wants to scan the code to authorize web login.

**Comment by lovethiscode** [comment]
@totynho i can do that, but now have no time.
